# Generated by Django 2.1.7 on 2019-03-25 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculadora',
            name='operator',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
